version: '3.0'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RUBY_VERSION: '2.7-slim-buster'
        NODE_MAJOR: '12'
        YARN_VERSION: '1.21.0'
    volumes:
      - .:/app
      - bundle:/bundle
      - node_modules:/app/node_modules
    tty: true
    stdin_open: true

  terraform:
    image: hashicorp/terraform:light
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform
    env_file:
      - .env
    tty: true
    stdin_open: true

volumes:
  bundle:
  node_modules:
