version: '3.0'
services:
  web:
    build: .
    volumes:
      - .:/app
      - bundle:/bundle
    tty: true
    stdin_open: true

  terraform:
    image: hashicorp/terraform:light
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform
    env_file:
      - .env
    tty: true
    stdin_open: true

volumes:
  bundle:
